library(lubridate)
library(forecast)
library(zoo)
library(tibbletime)
library(dplyr)
library(xts)
bseData <- read.csv("C:/Users/harsh/Downloads/BSESN.csv")
View(bseData)
str(bseData)
bseData$Date <- ymd(bseData$Date)
bseData$Open <- as.numeric(bseData$Open)
bseData$Open <- as.numeric(bseData$Open)
bseData$High <- as.numeric(bseData$High)
bseData$Low <- as.numeric(bseData$Low)
bseData$Close <- as.numeric(bseData$Close)
bseData$Adj.Close <- as.numeric(bseData$Adj.Close)
bseData$Volume <- as.numeric(bseData$Volume)
str(bseData)
sapply(bseData, function(x)sum(is.na(x)))
head(bseData)
tail(bseData)
par(mfrow=c(2,3))
plot(y = bseData$Adj.Close, x=bseData$Date, main = 'Adjusted Close Price of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
plot(y = bseData$Close, x=bseData$Date, main = 'Close Price of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
plot(y = bseData$Open, x=bseData$Date, main = 'Opening Price of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
plot(y = bseData$High, x=bseData$Date, main = 'Highest Price of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
plot(y = bseData$Low, x=bseData$Date, main = 'Lowest Price of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
plot(y = bseData$Volume, x=bseData$Date, main = 'Volume of S&P BSE SENSEX', ylab = 'Price', xlab = 'Date')
dplyr::mutate(bseData$year <- lubridate::year(bseData$Date))
dplyr::mutate(bseData$month <- lubridate::month(bseData$Date))
dplyr::mutate(bseData$day <- lubridate::day(bseData$Date))
na.locf(na.locf(bseData), fromLast = TRUE)
summary(bseData)
stocks <- xts(bseData[,-1], order.by = as.Date(bseData[,1],'%y/%m/%d'))
WeeklyData <- to.weekly(stocks, name = 'BSE')
MonthlyData <- to.monthly(stocks, name = 'BSEMonth')